# Generated by Django 4.1.5 on 2023-02-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=30)),
                ('precio_dia', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('balcon', models.BooleanField(default=False)),
                ('pileta', models.BooleanField(default=False)),
                ('mascotas', models.BooleanField(default=False)),
                ('max_personas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=40)),
                ('precio_dia', models.IntegerField()),
                ('seguro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_origen', models.CharField(max_length=40)),
                ('idioma', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paq_ubicacion', models.CharField(max_length=30)),
                ('paq_precio_aloja_dia', models.IntegerField()),
                ('paq_habitaciones', models.IntegerField()),
                ('paq_baños', models.IntegerField()),
                ('paq_balcon', models.BooleanField(default=False)),
                ('paq_pileta', models.BooleanField(default=False)),
                ('paq_mascotas', models.BooleanField(default=False)),
                ('paq_max_personas', models.IntegerField()),
                ('paq_interesa', models.BooleanField()),
                ('paq_marca', models.CharField(max_length=30)),
                ('paq_modelo', models.CharField(max_length=40)),
                ('paq_precio_auto_dia', models.IntegerField()),
                ('paq_seguro', models.BooleanField(default=False)),
            ],
        ),
    ]
