# Generated by Django 4.1.5 on 2023-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_de_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=245)),
            ],
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='descripcion',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='img_alojamiento',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='tipo',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='titulo',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='mascotas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='precio_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='ubicacion',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
