# Generated by Django 4.1.5 on 2023-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_usuarios_alojamientos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password1',
            field=models.CharField(default='NULL', max_length=8),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password2',
            field=models.CharField(default='NULL', max_length=8),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='NULL', max_length=245),
        ),
    ]
