# Generated by Django 4.1.5 on 2023-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_usuarios_password1_usuarios_password2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamientos',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
