# Generated by Django 4.1.5 on 2023-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alojamientos_reservado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamientos',
            name='reservado',
        ),
        migrations.RemoveField(
            model_name='autos',
            name='seguro',
        ),
        migrations.AddField(
            model_name='autos',
            name='img_auto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
