# Generated by Django 4.1.5 on 2023-03-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_alojamientos_reservado_remove_autos_seguro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
