# Generated by Django 4.1.5 on 2023-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_alojamientos_img_alojamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamientos',
            name='balcon',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='habitaciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='mascotas',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='pileta',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
