# Generated by Django 4.1.5 on 2023-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_alojamientos_balcon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamientos',
            name='baños',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alojamientos',
            name='max_personas',
            field=models.IntegerField(null=True),
        ),
    ]
