# Generated by Django 4.1.5 on 2023-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_alter_alojamientos_balcon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamientos',
            name='balcon',
            field=models.BooleanField(default='NULL', null=True),
        ),
    ]
