# Generated by Django 4.1.5 on 2023-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_remove_alojamientos_huesped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamientos',
            name='huesped',
            field=models.CharField(default='Desocupado', max_length=30),
        ),
    ]
