# Generated by Django 4.1.5 on 2023-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='titulo_alojamiento',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
