# Generated by Django 4.1.5 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_comentario_titulo_alojamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
