# Generated by Django 4.1.5 on 2023-03-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0022_alter_comentario_fechacomentario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Paquetes',
        ),
        migrations.DeleteModel(
            name='Pruebas',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RemoveField(
            model_name='alojamientos',
            name='huesped',
        ),
    ]
